### ISSUE TITLE
exposing filebot in container /usr/local/bin

### ISSUE THREAD

**Issue by dr01dy** [horjulf/docker-rutorrent-autodl#11]
Team,
Can you provide an guidance around exposing the container to use java in /usr/share along with filebot being in /usr/local/bin.

I'm trying to get rtorrent to call the rtorrent-postprocess.sh located iin /config/rtorrent/rtorrent-postprocess.sh

rtorrent.rc configuration 
`method.set_key=event.download.finished,filebot,"execute={/config/rtorrent/rtorrent-postprocess.sh,$d.base_path=,$d.name=,$d.custom1=}" `

root@110eddd3f87c:/# filebot
/usr/local/bin/filebot: line 57: /usr/share/java: Permission denied
root@110eddd3f87c:/#

**Comment by dr01dy** [comment]
I was able to get this resolved on my end.

`[apk add openjdk8](url)`
download filebot-portable

**Comment by horjulf** [comment]
That would work for runtime, just have to keep in mind that when recreating the container you will need to install the package again.
