### ISSUE TITLE
SyntaxError since last update

### ISSUE THREAD

**Issue by bilyboy785** [horjulf/docker-rutorrent-autodl#12]
Hello,

we've got an error since the last Docker Image update : 

`[04.01.2020 20:09:53] Bad response from server: (200 [parsererror,getplugins]) SyntaxError: Unexpected token '<'`

**Comment by horjulf** [comment]
Sometimes the plugins take too long to load and the UI will fail to fully load, it's a known issue with rutorrent, try disabling some plugins as many of them that are loaded by default are not necessary.
