### ISSUE TITLE
MyDialogManager

### ISSUE THREAD

**Issue by assbaby** [horjulf/docker-rutorrent-autodl#14]
I have been having a problem since a few days now.  I cannot seem to use autodl-irssi.  Nothing at all had changed when the problem began, since then I have removed the container and its data from /opt and then recreated the container.  Each time, I am seeing this problem when I try to access over the web:

[13.03.2020 06:19:55] MyDialogManager._onDownloadedFiles: Exception info: No settings found

The container appears to be running with no issue, I cannot find anything in the logs to suggest there is a problem.  I just cannot make any changes to autodl via web nor will autodl download anything.

**Comment by OctaneTwisted** [comment]
Also started seeing this error yesterday. It could be an autodl rutorrent plugin issue. Autodl itself seems to work fine and can still be configured through its config files, but any autodl-related menus don't open in rutorrent.

I deleted the container and re-created it with the existing /config mount and the same exact parameters. It worked for a while but I guess something updated and the issue came back.

I'm running Docker on Debian Buster.

**Comment by horjulf** [comment]
Theres been some breaking changes upstream in autodl-irssi, can you check with the latest develop build to see if the issue still occurs ?

Tag: `horjulf/rutorrent-autodl:develop`

**Comment by assbaby** [comment]
This has corrected the error.  Thank you!

**Comment by kvn1351** [comment]
Yup, it's fixed :)

**Comment by sorentorp** [comment]
I upgraded to develop, as described here. No luck - still get the error.

I guess it is related to https://github.com/autodl-community/autodl-irssi/issues/191

**Comment by horjulf** [comment]
Pushed the changes into master, since this specific issue comes from upstream autodl-irssi, I'm closing this issue for now as it might be a temporary error due to GitHub rate limiting.
Feel free to reopen if something can be done at image level to work around it.

**Comment by sorentorp** [comment]
Ok. Is there a fix I can do, so I dont have the problem?

**Comment by Escondido** [comment]
Has anybody figured out a solution?  

I'm also have the same issue when trying to access autodl plugin menu settings. Installing the developer edition does not fix the problem.

**Comment by sorentorp** [comment]
Any idea how to fix this, I still have the problem...
