### ISSUE TITLE
Upload speed seems to hover around 1 MB/s

### ISSUE THREAD

**Issue by lun4r** [horjulf/docker-rutorrent-autodl#16]
Hello Filipe!
I want to say thank you for the staff!  Everything works smooth, including irssi-autodl.
I have one problem however - while my download speed goes up to 22 MB/s at times, my upload speed always seems to hover around 1MB/s. This is barely 1% of my internet connection.
I am using synology 918+ NAS. 4x4 TB HDD in Synology Hybrid Raid. 
Rtorrent port is forwarding  througn Keenitic giga and and the port sensor in rutorrent lights up green.
Here is my speedtest in the container 
https://imgur.com/AfATgjN
I really have no clue why the upload speed seems so slow. 
I checked the router, dropped it into default. Same with Synology NAS.
Nothing helps...

**Comment by horjulf** [comment]
Theres too many factors that affect speed, take a look at https://github.com/rakshasa/rtorrent/wiki/Performance-Tuning

Rtorrent hasn't been actively developed in quite a while, I would recommend using https://hub.docker.com/r/sc4h/qbittorrent
https://gitlab.com/sc4h/docker-qbittorrent
