### ISSUE TITLE
Rutorrent 3.10 beta

### ISSUE THREAD

**Issue by IvanShift** [horjulf/docker-rutorrent-autodl#18]
Hello!
Could you change Rutorrent 3.9 to Rutorrent 3.10 in develop-version of you container?

**Comment by horjulf** [comment]
It already uses the master branch of Rutorrent, to update just restart the container.
https://github.com/horjulf/docker-rutorrent-autodl/blob/master/root/etc/cont-init.d/30-getautodl#L7

**Comment by IvanShift** [comment]
Could you recheck it, please?
Or could you explain more detail how to upgrade rutorrent to 3.10? I restarted container without any effect. 

![изображение](https://user-images.githubusercontent.com/64527940/81901272-e9fda980-95c6-11ea-9a86-2f047721a579.png)

**Comment by horjulf** [comment]
The image uses the master branch of ruTorrent, not releases from GH.
Sorry I confused the git pull with autodl-irssi, it doesn't update ruTorrent on container restart but its updated when the container is built (every 2 weeks).

Latest build was 9 days ago, so it would have grabbed the commit `f2960a54fccf8b448ae37f8310df934fd3d7039c`.
https://github.com/Novik/ruTorrent/commits/master

ruTorrent hasn't made "releases" in a long time, the version in the image is much more recent that the releases in GH.

**Comment by IvanShift** [comment]
Latest develop build is not working:

> 
>  # Checking rtorrent session lock /detach_sess/.rtorrent
> # rtorrent dtach session started 518
> # irssi/autodl dtach session finished 513
> # rtorrent dtach session finished 518
> # Checking irssi/autodl session lock /detach_sess/.autodl
> # irssi/autodl dtach session started 526
> # irssi/autodl dtach session finished 526
> # Checking rtorrent session lock /detach_sess/.rtorrent
> # rtorrent dtach session started 532
> # rtorrent dtach session finished 532

What is exact difference between release and develop version?
