### ISSUE TITLE
Latest build is not working

### ISSUE THREAD

**Issue by IvanShift** [horjulf/docker-rutorrent-autodl#19]
Hello!
Container does not start:
![изображение](https://user-images.githubusercontent.com/64527940/82125494-f5132e00-97ae-11ea-9a0a-cb9429c1b007.png)

Could you fix it?

**Comment by horjulf** [comment]
Check your rtorrent config and the logs at `/config/log`, there hasn't been any changes recently other than the biweekly image rebuild with the latest base OS layer.

**Comment by IvanShift** [comment]
Hello!
It's  something wrong with docker container. Because I updated "developer" version and receive this problem. After 2 day later I updated "latest" version and receive the same error. All logs are empty. I also delete and recreate config-dir but situation is the same.
Could you please recheck it?

**Comment by IvanShift** [comment]
I solve it. Sorry for fake error. After update I forget to add PGID and PUID. Maybe you will add this params to be shown in Environment Variables ?
![изображение](https://user-images.githubusercontent.com/64527940/82253119-fed89500-9958-11ea-92d0-d7f460cdc6db.png)

**Comment by horjulf** [comment]
The vars are consumed by s6 directly, setting them by default would break backwards compatibility.

**Comment by IvanShift** [comment]
But if I do not fill those variables container will not start at anyway. So this is reason to add them.
