### ISSUE TITLE
Where to place files when migrating to docker container?

### ISSUE THREAD

**Issue by BRTPOB** [horjulf/docker-rutorrent-autodl#21]
I've currently got an ruTorrent/autodl-irssi setup that I'm trying to migrate to your docker container, and I've got it up and running but I don't see where I should be putting my config files from autodl-irssi so I can just shut the old one down and switch to the docker container. Where should I be putting my config files for the autodl-irssi stuff?

Thanks!

**Comment by horjulf** [comment]
Config files for irssi will be at `/config/.irssi/`, autodl at `/config/.autodl/`.
https://github.com/horjulf/docker-rutorrent-autodl/blob/master/root/etc/cont-init.d/30-getautodl
