### ISSUE TITLE
Adding additioanal tracker files

### ISSUE THREAD

**Issue by esran** [horjulf/docker-rutorrent-autodl#22]
It looks like there is no way to permanently add a new tracker file. On startup it forces a clean update of the tracker repo which will delete any unrecognised files.

Is there a way to work round this?
If not, any chance of a way to add tracker files to the config?

**Comment by horjulf** [comment]
Unfortunately upstream force-pushes commits from time to time, thats the reason I had to delete untracked/conflicted files to avoid breaking updates for the majority. Can always add an environment variable to toggle the logic, feel free to submit a PR.
I would recommend migrating to https://gitlab.com/cloudb0x/trackarr which is actively developed and supported.
