### ISSUE TITLE
Please update config.php 

### ISSUE THREAD

**Issue by IvanShift** [horjulf/docker-rutorrent-autodl#24]
File conf/config.php was updated 9 month:

https://github.com/Novik/ruTorrent/issues/2056
https://github.com/Novik/ruTorrent/commit/0da161d21a1d2d850b079b52e70f0138bcac2cfe

It is still old now:
![screenshot](https://user-images.githubusercontent.com/64527940/99765424-182cea80-2b10-11eb-8744-0934180f4293.png)

**Comment by horjulf** [comment]
Updated, thanks!
