### ISSUE TITLE
Unable to move file once Downloaded

### ISSUE THREAD

**Issue by thatsnasty** [horjulf/docker-rutorrent-autodl#27]
Hello,

I have a cloudbox install, and for the past few weeks I have been unable to move a downloaded file to a new location.

I select the file and right click and select 'Save To..." I change the location, click ok which then greys out and then it just hangs [here](https://imgur.com/yRH5Eoc)

From the nginx error log I'm able to find this
```2021/02/22 09:06:03 [error] 437#437: *8406 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function ctype_xdigit() in /app/rutorrent/plugins/datadir/action.php:36
Stack trace:
#0 {main}
  thrown in /app/rutorrent/plugins/datadir/action.php on line 36" while reading response header from upstream, client: 172.18.0.12, server: _, request: "POST /plugins/datadir/action.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "rutorrent.mydomain.tld", referrer: "https://rutorrent.mydomain.tld/"
```

Which implies ctype_xdigit is not defined, but it is built into php? 

That's about as much as I can give you, I believe I'm correct in thinking this isn't cloudbox specific, I have tried it on 2 different installs on different VPS and still come up the same.

Thank you.

**Comment by horjulf** [comment]
Hi,

Looks like the plugin is using new functions, pushed a fix into develop, can you try `horjulf/rutorrent-autodl:develop` ?

**Comment by thatsnasty** [comment]
Develop working as expected, thank you very much!

**Comment by horjulf** [comment]
Thanks, pushed into latest.
