### ISSUE TITLE
Readme/branding confusion

### ISSUE THREAD

**Issue by aptalca** [horjulf/docker-rutorrent-autodl#4]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

Hey there,

I'm one of the linuxserver.io team members. We noticed that your image on docker hub (as well as this git repo) still has the linuxserver.io readme, which is very confusing to users. We kindly ask that you edit the info to clarify that it is your fork and users should contact you with issues and requests.

To be clear, it is perfectly fine for you to maintain and publish your own fork. But make sure that it has your branding and not ours.

Thanks

**Comment by horjulf** [comment]
Sure, I've removed the branding and left a reference in the README, cheers.
