### ISSUE TITLE
Could not read SSL: Unknown Error code 5

### ISSUE THREAD

**Issue by Soulplayer** [horjulf/docker-rutorrent-autodl#8]
Hello,

I'm currently having problems with autodl. It won't download using https anymore? Complete error:
Error downloading torrent file https:///xxxxxxxxx.torrent. Error: _onReadAvaialble ex: could not read: SSL: Unknown error code: 5

Tips?

**Comment by horjulf** [comment]
Fixed in cda323e8bee557130d6d67cd374dc5d157645eda by rolling back to alpine 3.8.
