### ISSUE TITLE
Plugin/Themes

### ISSUE THREAD

**Issue by dr01dy** [horjulf/docker-rutorrent-autodl#9]
Can you provide any instruction for getting themes to work with rutorrent.

**Comment by bilyboy785** [comment]
Hello @dr01dy , you can copy your plugin in docker system /app/rutorrent/plugins with docker exec.

**Comment by horjulf** [comment]
You can put the themes at `/config/themes`, they will be copied at startup into the rutorrent folder.
Same applies for plugins at `/config/plugins`.

https://github.com/horjulf/docker-rutorrent-autodl/blob/master/root/etc/cont-init.d/50-config#L26
